// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../vendor/github.com/streadway/amqp/delivery.go

// Package rabbitmqconsum_test is a generated GoMock package.
package rabbitmqconsum_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAcknowledger is a mock of Acknowledger interface.
type MockAcknowledger struct {
	ctrl     *gomock.Controller
	recorder *MockAcknowledgerMockRecorder
}

// MockAcknowledgerMockRecorder is the mock recorder for MockAcknowledger.
type MockAcknowledgerMockRecorder struct {
	mock *MockAcknowledger
}

// NewMockAcknowledger creates a new mock instance.
func NewMockAcknowledger(ctrl *gomock.Controller) *MockAcknowledger {
	mock := &MockAcknowledger{ctrl: ctrl}
	mock.recorder = &MockAcknowledgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcknowledger) EXPECT() *MockAcknowledgerMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockAcknowledger) Ack(tag uint64, multiple bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", tag, multiple)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockAcknowledgerMockRecorder) Ack(tag, multiple interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockAcknowledger)(nil).Ack), tag, multiple)
}

// Nack mocks base method.
func (m *MockAcknowledger) Nack(tag uint64, multiple, requeue bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nack", tag, multiple, requeue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Nack indicates an expected call of Nack.
func (mr *MockAcknowledgerMockRecorder) Nack(tag, multiple, requeue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nack", reflect.TypeOf((*MockAcknowledger)(nil).Nack), tag, multiple, requeue)
}

// Reject mocks base method.
func (m *MockAcknowledger) Reject(tag uint64, requeue bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", tag, requeue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reject indicates an expected call of Reject.
func (mr *MockAcknowledgerMockRecorder) Reject(tag, requeue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockAcknowledger)(nil).Reject), tag, requeue)
}
